### ISSUE TITLE
Mail logger: Call to undefined method setplugin

### ISSUE THREAD

**Issue by StalkAlex** [yiisoft/yii2-swiftmailer#43]
Just enabled logs ` 'enableSwiftMailerLogging' => true` and got the error below
```
PHP User Error – yii\base\ErrorException

Call to undefined method setplugin
1. in /vagrant/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php at line 291
282283284285286287288289290291292293294295296297298299300                $return = call_user_func_array(array($handler, $method), $args);
                // Allow fluid method calls
                if (is_null($return) && substr($method, 0, 3) == 'set') {
                    return $this;
                } else {
                    return $return;
                }
            }
        }
        trigger_error('Call to undefined method '.$method, E_USER_ERROR);
    }
 
    /** Get the params to initialize the buffer */
    protected function _getBufferParams()
    {
        return $this->_params;
    }
 
    /** Overridden to perform EHLO instead */
2. in /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php at line 239 – Swift_Transport_EsmtpTransport::__call('method' => '???', 'args' => '???')
233234235236237238239240241242243244245            foreach ($config as $name => $value) {
                if ($reflection->hasProperty($name) && $reflection->getProperty($name)->isPublic()) {
                    $object->$name = $value;
                } else {
                    $setter = 'set' . $name;
                    if ($reflection->hasMethod($setter) || $reflection->hasMethod('__call')) {
                        $object->$setter($value);
                    } else {
                        throw new InvalidConfigException('Setting unknown property: ' . $className . '::' . $name);
                    }
                }
            }
        }
3. in /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php at line 239 –
An Error occurred while handling another error:
ReflectionException: Method Swift_Transport_EsmtpTransport::setplugin() does not exist in /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('Swift_Transport...', 'setplugin')
#1 /vagrant/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('Swift_Transport...')
#2 /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/vagrant/vendor...')
#3 /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php(307): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#4 /vagrant/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem('/vagrant/vendor...', 238, 'Swift_Transport...', 'setplugin', Array, 3)
#5 /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php(249): require('/vagrant/vendor...')
#6 /vagrant/vendor/yiisoft/yii2/web/ErrorHandler.php(113): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#7 /vagrant/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#8 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#9 {main}
Previous exception:
yii\base\ErrorException: Call to undefined method setplugin in /vagrant/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:291
Stack trace:
#0 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(239): Swift_Transport_EsmtpTransport->__call('???', '???')
#1 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(239): Swift_Transport_EsmtpTransport->setplugin('???')
#2 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(188): yii\swiftmailer\Mailer->createSwiftObject('???')
#3 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(129): yii\swiftmailer\Mailer->createTransport('???')
#4 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(155): yii\swiftmailer\Mailer->getTransport()
#5 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(105): yii\swiftmailer\Mailer->createSwiftMailer()
#6 /vagrant/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): yii\swiftmailer\Mailer->getSwiftMailer()
#7 /vagrant/vendor/yiisoft/yii2/mail/BaseMailer.php(262): yii\swiftmailer\Mailer->sendMessage('???')
#8 /vagrant/vendor/yiisoft/yii2/mail/BaseMessage.php(48): yii\mail\BaseMailer->send('???')
#9 /vagrant/src/components/Mailer.php(60): yii\mail\BaseMessage->send('???')
#10 /vagrant/src/modules/backend/controllers/DefaultController.php(77): app\components\Mailer->sendMailTo('???', '???', '???', '???')
#11 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): app\modules\backend\controllers\DefaultController->actionSendEmail()
#12 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/vagrant/vendor/yiisoft/yii2/base/InlineAction.php:57}('???', '???')
#13 /vagrant/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams('???')
#14 /vagrant/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('???', '???')
#15 /vagrant/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('???', '???')
#16 /vagrant/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest('???')
#17 /vagrant/web/index.php(14): yii\base\Application->run()
#18 {main}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.1
| PHP version      | 7.1.1
| Operating system | CentOs 7

**Comment by klimov-paul** [comment]
Unable to reproduce. Enabling `enableSwiftMailerLogging` parameter runs correctly.
Method `setPlugin()` is never called during this setting processing.
The only way it may appear if you used `plugin` key among transport config, e.g.:
```php
'mailer' => [
    'class' => 'yii\swiftmailer\Mailer',
    'enableSwiftMailerLogging' => true,
    'transport' => [
         'class' => 'EsmtpTransport',
         'plugin' => ??? // error producing string
    ],
],
```
